"""Create model

Revision ID: 0bd36dbb9974
Revises: 4e81a1f09f3c
Create Date: 2022-11-26 18:46:57.529651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd36dbb9974'
down_revision = '4e81a1f09f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
