"""Fixed

Revision ID: 4e81a1f09f3c
Revises: 8f820caf7bcd
Create Date: 2022-11-16 19:04:54.014809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e81a1f09f3c'
down_revision = '8f820caf7bcd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=32), nullable=False))
    op.drop_column('user', 'roles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roles', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###