"""Create tables

Revision ID: 8f820caf7bcd
Revises: 
Create Date: 2022-11-16 18:29:47.728516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f820caf7bcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problem',
    sa.Column('problemid', sa.Integer(), nullable=False),
    sa.Column('branch', sa.Enum('screen', 'battery', 'button', 'os', 'hardware', 'other', name='branchenum'), nullable=False),
    sa.Column('daysToSolve', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('problemid')
    )
    op.create_table('service_center',
    sa.Column('serviceid', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=45), nullable=False),
    sa.Column('adress', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=False),
    sa.Column('rating', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('serviceid')
    )
    op.create_table('user',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.Column('userStatus', sa.Enum('inactive', 'active', name='userstatus'), nullable=False),
    sa.Column('service_centerid', sa.Integer(), nullable=True),
    sa.Column('roles', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['service_centerid'], ['service_center.serviceid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('deviceid', sa.Integer(), nullable=False),
    sa.Column('firm', sa.String(length=45), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=False),
    sa.Column('status', sa.Enum('arrived', 'in_work', 'ready', name='devicestatus'), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.userid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deviceid')
    )
    op.create_table('problem_to_device',
    sa.Column('problemid', sa.Integer(), nullable=True),
    sa.Column('deviceid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deviceid'], ['device.deviceid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['problemid'], ['problem.problemid'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_to_device')
    op.drop_table('device')
    op.drop_table('user')
    op.drop_table('service_center')
    op.drop_table('problem')
    # ### end Alembic commands ###
